image: docker

services: 
  - docker:dind
   
stages:
  - build

build docker image:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/fcagil/com.fcagroup.wisdom.chef-docker-runner-image:$CI_BUILD_REF_NAME .
    - docker push registry.gitlab.com/fcagil/com.fcagroup.wisdom.chef-docker-runner-image:$CI_BUILD_REF_NAME