image: docker

services: 
  - docker:dind
   
stages:
  - build

before_script:
  - chmod +x test.sh

build docker image:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/fcagil/com.fcagroup.wisdom.chef-docker-runner-image:$CI_BUILD_REF_NAME .
    - docker run -it registry.gitlab.com/fcagil/com.fcagroup.wisdom.chef-docker-runner-image:$CI_BUILD_REF_NAME /bin/bash -c "/opt/chefdk/bin/chef -v && docker -v"
    - docker push registry.gitlab.com/fcagil/com.fcagroup.wisdom.chef-docker-runner-image:$CI_BUILD_REF_NAME